;this file for FamiTone5.1 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


soundtrack_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Insert song here

@instruments:
	.word @env1,@env0,@env0,@env2

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c5,$c8,$ca,$c7,$c4,$c2,$c2,$c0,$00,$07
@env2:
	.byte $c2,$00,$00


; Insert song here
@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $80,$1c,$85,$20,$85,$23,$85,$20,$85,$1c,$dd
	.byte $fd
	.word @song0ch0loop

; Insert song here
@song0ch1:
@song0ch1loop:
@ref1:
	.byte $f9,$85
	.byte $fd
	.word @song0ch1loop

; Insert song here
@song0ch2:
@song0ch2loop:
@ref2:
	.byte $f9,$85
	.byte $fd
	.word @song0ch2loop

; Insert song here
@song0ch3:
@song0ch3loop:
@ref3:
	.byte $f9,$85
	.byte $fd
	.word @song0ch3loop

; Insert song here
@song0ch4:
@song0ch4loop:
@ref4:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop
