;
; File generated by cc65 v 2.19 - Git 4f87c7cc6
;
	.fopt		compiler,"cc65 v 2.19 - Git 4f87c7cc6"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "src/enemies.c", 984, 1636938317
	.dbg		file, "src/lib/subrand.h", 111, 1636932251
	.dbg		file, "src/entities.h", 598, 1636938068
	.dbg		file, "src/enemies.h", 90, 1636937521
	.dbg		file, "src/dungeon.h", 606, 1636937603
	.dbg		file, "src/../assets/enemy-stats.h", 234, 1636921980
	.dbg		sym, "subrand8", "00", extern, "_subrand8"
	.dbg		sym, "party_level", "00", extern, "_party_level"
	.dbg		sym, "current_sector_index", "00", extern, "_current_sector_index"
	.dbg		sym, "enemy_difficulty", "00", extern, "_enemy_difficulty"
	.dbg		sym, "i", "00", extern, "_i"
	.import		_subrand8
	.import		_party_level
	.export		_select_enemy_type
	.import		_current_sector_index
	.import		_enemy_difficulty
	.importzp	_i
	.export		_average_difficulty
	.export		_min_difficulty
	.export		_eligible_types
	.export		_num_eligible_types

.segment	"RODATA"

.segment	"RODATA"

.segment	"BSS"

.segment	"ZEROPAGE"
_average_difficulty:
	.res	1,$00
_min_difficulty:
	.res	1,$00
.segment	"BSS"
_eligible_types:
	.res	5,$00
_num_eligible_types:
	.res	1,$00

; ---------------------------------------------------------------
; unsigned char __near__ select_enemy_type (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_select_enemy_type: near

	.dbg	func, "select_enemy_type", "00", extern, "_select_enemy_type"

.segment	"CODE"

;
; average_difficulty = (party_level + current_sector_index + 1) / 2;
;
	.dbg	line, "src/enemies.c", 26
	ldx     #$00
	lda     _party_level
	clc
	adc     _current_sector_index
	bcc     L0015
	inx
	clc
L0015:	adc     #$01
	bcc     L0002
	inx
L0002:	cpx     #$00
	bpl     L0003
	sta     regsave
	stx     regsave+1
	cpx     #$FF
	bne     L0005
	cmp     #$FF
L0005:	jsr     boolult
	lsr     a
	lda     regsave
	ldx     regsave+1
	bcs     L0003
	lda     #$00
	jmp     L0016
L0003:	jsr     asrax1
L0016:	sta     _average_difficulty
;
; min_difficulty = (current_sector_index + 1) / 6;
;
	.dbg	line, "src/enemies.c", 27
	ldx     #$00
	lda     _current_sector_index
	clc
	adc     #$01
	bcc     L0006
	inx
L0006:	jsr     pushax
	lda     #$06
	jsr     tosdiva0
	sta     _min_difficulty
;
; for(i = 0; i < NUM_ENEMY_TYPES; i++) {
;
	.dbg	line, "src/enemies.c", 28
	lda     #$00
	sta     _i
L0017:	lda     _i
	cmp     #$05
	bcs     L001B
;
; if (enemy_difficulty[i] <= average_difficulty &&
;
	.dbg	line, "src/enemies.c", 29
	ldy     _i
	lda     _enemy_difficulty,y
	cmp     _average_difficulty
	beq     L0014
	bcs     L001A
;
; enemy_difficulty[i] >= min_difficulty) {
;
	.dbg	line, "src/enemies.c", 30
L0014:	ldy     _i
	lda     _enemy_difficulty,y
	cmp     _min_difficulty
	bcc     L001A
;
; eligible_types[num_eligible_types++] = i;
;
	.dbg	line, "src/enemies.c", 31
	lda     _num_eligible_types
	inc     _num_eligible_types
	clc
	adc     #<(_eligible_types)
	sta     ptr1
	lda     #$00
	adc     #>(_eligible_types)
	sta     ptr1+1
	lda     _i
	ldy     #$00
	sta     (ptr1),y
;
; for(i = 0; i < NUM_ENEMY_TYPES; i++) {
;
	.dbg	line, "src/enemies.c", 28
L001A:	inc     _i
	jmp     L0017
;
; i = subrand8(num_eligible_types - 1);
;
	.dbg	line, "src/enemies.c", 34
L001B:	lda     _num_eligible_types
	sec
	sbc     #$01
	jsr     _subrand8
	sta     _i
;
; return eligible_types[i];
;
	.dbg	line, "src/enemies.c", 35
	ldy     _i
	ldx     #$00
	lda     _eligible_types,y
;
; }
;
	.dbg	line, "src/enemies.c", 36
	rts

	.dbg	line
.endproc

