;
; File generated by cc65 v 2.19 - Git 4f87c7cc6
;
	.fopt		compiler,"cc65 v 2.19 - Git 4f87c7cc6"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "src/entities.c", 999, 1636758179
	.dbg		file, "src/entities.h", 304, 1636758409
	.dbg		file, "src/../assets/sprites.h", 602, 1636691396
	.dbg		file, "src/../assets/../src/constants.h", 48, 1635896270
	.dbg		sym, "entity_turn", "00", extern, "_entity_turn"
	.export		_init_entities
	.export		_entity_handler
	.import		_entity_turn
	.export		_num_entities
	.export		_entity_x
	.export		_entity_y
	.export		_entity_type
	.export		_entity_turn_counter
	.export		_entity_speed
	.export		_current_entity
	.export		_current_entity_state
	.export		_next_entity

.segment	"RODATA"

.segment	"RODATA"

.segment	"BSS"

.segment	"ZEROPAGE"
_num_entities:
	.res	1,$00
.segment	"BSS"
_entity_x:
	.res	8,$00
_entity_y:
	.res	8,$00
_entity_type:
	.res	8,$00
_entity_turn_counter:
	.res	8,$00
_entity_speed:
	.res	8,$00
_current_entity:
	.res	1,$00
_current_entity_state:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ init_entities (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_entities: near

	.dbg	func, "init_entities", "00", extern, "_init_entities"

.segment	"CODE"

;
; num_entities = 0;
;
	.dbg	line, "src/entities.c", 29
	lda     #$00
	sta     _num_entities
;
; current_entity = 0;
;
	.dbg	line, "src/entities.c", 30
	sta     _current_entity
;
; }
;
	.dbg	line, "src/entities.c", 31
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ entity_handler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_entity_handler: near

	.dbg	func, "entity_handler", "00", extern, "_entity_handler"

.segment	"CODE"

;
; }
;
	.dbg	line, "src/entities.c", 35
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ next_entity (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_next_entity: near

	.dbg	func, "next_entity", "00", extern, "_next_entity"

.segment	"CODE"

;
; if (num_entities == 0) return;
;
	.dbg	line, "src/entities.c", 38
	lda     _num_entities
	bne     L0003
	rts
;
; if (entity_turn()) {
;
	.dbg	line, "src/entities.c", 41
L0003:	jsr     _entity_turn
	tax
;
; break;
;
	.dbg	line, "src/entities.c", 42
	bne     L0004
;
; ++current_entity;
;
	.dbg	line, "src/entities.c", 44
	inc     _current_entity
;
; if (current_entity >= num_entities) {
;
	.dbg	line, "src/entities.c", 45
	lda     _current_entity
	cmp     _num_entities
	bcc     L0003
;
; current_entity = 0;
;
	.dbg	line, "src/entities.c", 46
	stx     _current_entity
;
; while(1) {
;
	.dbg	line, "src/entities.c", 40
	jmp     L0003
;
; }
;
	.dbg	line, "src/entities.c", 49
L0004:	rts

	.dbg	line
.endproc

