;
; File generated by cc65 v 2.19 - Git 6c90f3e2
;
	.fopt		compiler,"cc65 v 2.19 - Git 6c90f3e2"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "src/nametable_loader.c", 857, 1636239847
	.dbg		file, "src/lib/nesdoug.h", 6692, 1635896270
	.dbg		sym, "multi_vram_buffer_horz", "00", extern, "_multi_vram_buffer_horz"
	.import		_multi_vram_buffer_horz
	.export		_nametable_buffer
	.export		_current_nametable_address
	.export		_nametable_slice_counter
	.export		_set_nametable_loader_buffer
	.export		_start_nametable_loader
	.export		_yield_nametable_loader

.segment	"RODATA"

.segment	"RODATA"

.segment	"BSS"

.segment	"ZEROPAGE"
_nametable_buffer:
	.res	2,$00
_current_nametable_address:
	.res	2,$00
_nametable_slice_counter:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ set_nametable_loader_buffer (unsigned char *buffer)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_set_nametable_loader_buffer: near

	.dbg	func, "set_nametable_loader_buffer", "00", extern, "_set_nametable_loader_buffer"
	.dbg	sym, "buffer", "00", auto, 0

.segment	"CODE"

;
; void set_nametable_loader_buffer(unsigned char * buffer) {
;
	.dbg	line, "src/nametable_loader.c", 15
	jsr     pushax
;
; nametable_buffer = buffer;
;
	.dbg	line, "src/nametable_loader.c", 16
	ldy     #$01
	lda     (sp),y
	sta     _nametable_buffer+1
	dey
	lda     (sp),y
	sta     _nametable_buffer
;
; }
;
	.dbg	line, "src/nametable_loader.c", 17
	jmp     incsp2

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ start_nametable_loader (unsigned int nametable_address)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_start_nametable_loader: near

	.dbg	func, "start_nametable_loader", "00", extern, "_start_nametable_loader"
	.dbg	sym, "nametable_address", "00", auto, 0

.segment	"CODE"

;
; void start_nametable_loader(unsigned int nametable_address) {
;
	.dbg	line, "src/nametable_loader.c", 19
	jsr     pushax
;
; current_nametable_address = nametable_address;
;
	.dbg	line, "src/nametable_loader.c", 20
	ldy     #$01
	lda     (sp),y
	sta     _current_nametable_address+1
	dey
	lda     (sp),y
	sta     _current_nametable_address
;
; nametable_slice_counter = 0;
;
	.dbg	line, "src/nametable_loader.c", 21
	sty     _nametable_slice_counter
;
; }
;
	.dbg	line, "src/nametable_loader.c", 22
	jmp     incsp2

	.dbg	line
.endproc

; ---------------------------------------------------------------
; unsigned char __near__ yield_nametable_loader (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_yield_nametable_loader: near

	.dbg	func, "yield_nametable_loader", "00", extern, "_yield_nametable_loader"

.segment	"CODE"

;
; if (nametable_slice_counter >= NUM_SLICES) return 0;
;
	.dbg	line, "src/nametable_loader.c", 25
	lda     _nametable_slice_counter
	cmp     #$10
	bcc     L0002
	ldx     #$00
	txa
	rts
;
; multi_vram_buffer_horz(nametable_buffer, SLICE_SIZE, current_nametable_address);
;
	.dbg	line, "src/nametable_loader.c", 27
L0002:	jsr     decsp3
	lda     _nametable_buffer
	ldy     #$01
	sta     (sp),y
	iny
	lda     _nametable_buffer+1
	sta     (sp),y
	lda     #$40
	ldy     #$00
	sta     (sp),y
	lda     _current_nametable_address
	ldx     _current_nametable_address+1
	jsr     _multi_vram_buffer_horz
;
; nametable_buffer += SLICE_SIZE;
;
	.dbg	line, "src/nametable_loader.c", 29
	lda     #$40
	clc
	adc     _nametable_buffer
	sta     _nametable_buffer
	bcc     L0003
	inc     _nametable_buffer+1
;
; current_nametable_address += SLICE_SIZE;
;
	.dbg	line, "src/nametable_loader.c", 30
L0003:	lda     #$40
	clc
	adc     _current_nametable_address
	sta     _current_nametable_address
	bcc     L0004
	inc     _current_nametable_address+1
;
; ++nametable_slice_counter;
;
	.dbg	line, "src/nametable_loader.c", 32
L0004:	inc     _nametable_slice_counter
;
; return 1;
;
	.dbg	line, "src/nametable_loader.c", 33
	ldx     #$00
	lda     #$01
;
; }
;
	.dbg	line, "src/nametable_loader.c", 34
	rts

	.dbg	line
.endproc

