;
; File generated by cc65 v 2.19 - Git 4f87c7cc6
;
	.fopt		compiler,"cc65 v 2.19 - Git 4f87c7cc6"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "src/players.c", 519, 1636761637
	.dbg		file, "src/players.h", 566, 1636761601
	.dbg		sym, "player_str", "00", extern, "_player_str"
	.dbg		sym, "player_int", "00", extern, "_player_int"
	.dbg		sym, "player_wis", "00", extern, "_player_wis"
	.dbg		sym, "player_dex", "00", extern, "_player_dex"
	.dbg		sym, "player_con", "00", extern, "_player_con"
	.dbg		sym, "player_hp", "00", extern, "_player_hp"
	.dbg		sym, "player_max_hp", "00", extern, "_player_max_hp"
	.dbg		sym, "player_mp", "00", extern, "_player_mp"
	.dbg		sym, "player_max_mp", "00", extern, "_player_max_mp"
	.dbg		sym, "player_xp", "00", extern, "_player_xp"
	.dbg		sym, "player_lv", "00", extern, "_player_lv"
	.dbg		sym, "player_class", "00", extern, "_player_class"
	.dbg		sym, "i", "00", extern, "_i"
	.import		_player_str
	.import		_player_int
	.import		_player_wis
	.import		_player_dex
	.import		_player_con
	.import		_player_hp
	.import		_player_max_hp
	.import		_player_mp
	.import		_player_max_mp
	.import		_player_xp
	.import		_player_lv
	.import		_player_class
	.export		_initialize_party
	.importzp	_i

.segment	"RODATA"

.segment	"RODATA"

; ---------------------------------------------------------------
; void __near__ initialize_party (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_initialize_party: near

	.dbg	func, "initialize_party", "00", extern, "_initialize_party"

.segment	"CODE"

;
; for(i = 0; i < 4; i++) {
;
	.dbg	line, "src/players.c", 11
	lda     #$00
	sta     _i
L0018:	lda     _i
	cmp     #$04
	bcc     L0019
;
; }
;
	.dbg	line, "src/players.c", 25
	rts
;
; player_str[i] = 1;
;
	.dbg	line, "src/players.c", 12
L0019:	ldy     _i
	lda     #$01
	sta     _player_str,y
;
; player_int[i] = 1;
;
	.dbg	line, "src/players.c", 13
	ldy     _i
	sta     _player_int,y
;
; player_wis[i] = 1;
;
	.dbg	line, "src/players.c", 14
	ldy     _i
	sta     _player_wis,y
;
; player_dex[i] = 1;
;
	.dbg	line, "src/players.c", 15
	ldy     _i
	sta     _player_dex,y
;
; player_con[i] = 1;
;
	.dbg	line, "src/players.c", 16
	ldy     _i
	sta     _player_con,y
;
; player_hp[i] = 10;
;
	.dbg	line, "src/players.c", 17
	ldx     #$00
	lda     _i
	asl     a
	bcc     L0012
	inx
	clc
L0012:	adc     #<(_player_hp)
	sta     ptr1
	txa
	adc     #>(_player_hp)
	sta     ptr1+1
	lda     #$0A
	ldy     #$00
	sta     (ptr1),y
	iny
	lda     #$00
	sta     (ptr1),y
;
; player_max_hp[i] = 10;
;
	.dbg	line, "src/players.c", 18
	tax
	lda     _i
	asl     a
	bcc     L0013
	inx
	clc
L0013:	adc     #<(_player_max_hp)
	sta     ptr1
	txa
	adc     #>(_player_max_hp)
	sta     ptr1+1
	lda     #$0A
	dey
	sta     (ptr1),y
	iny
	lda     #$00
	sta     (ptr1),y
;
; player_mp[i] = 10;
;
	.dbg	line, "src/players.c", 19
	tax
	lda     _i
	asl     a
	bcc     L0014
	inx
	clc
L0014:	adc     #<(_player_mp)
	sta     ptr1
	txa
	adc     #>(_player_mp)
	sta     ptr1+1
	lda     #$0A
	dey
	sta     (ptr1),y
	iny
	lda     #$00
	sta     (ptr1),y
;
; player_max_mp[i] = 10;
;
	.dbg	line, "src/players.c", 20
	tax
	lda     _i
	asl     a
	bcc     L0015
	inx
	clc
L0015:	adc     #<(_player_max_mp)
	sta     ptr1
	txa
	adc     #>(_player_max_mp)
	sta     ptr1+1
	lda     #$0A
	dey
	sta     (ptr1),y
	iny
	lda     #$00
	sta     (ptr1),y
;
; player_xp[i] = 0;
;
	.dbg	line, "src/players.c", 21
	tax
	lda     _i
	asl     a
	bcc     L0016
	inx
	clc
L0016:	adc     #<(_player_xp)
	sta     ptr1
	txa
	adc     #>(_player_xp)
	sta     ptr1+1
	lda     #$00
	dey
	sta     (ptr1),y
	iny
	sta     (ptr1),y
;
; player_lv[i] = 1;
;
	.dbg	line, "src/players.c", 22
	tax
	lda     _i
	asl     a
	bcc     L0017
	inx
	clc
L0017:	adc     #<(_player_lv)
	sta     ptr1
	txa
	adc     #>(_player_lv)
	sta     ptr1+1
	tya
	dey
	sta     (ptr1),y
	iny
	lda     #$00
	sta     (ptr1),y
;
; player_class[i] = Fighter;
;
	.dbg	line, "src/players.c", 23
	ldy     _i
	sta     _player_class,y
;
; for(i = 0; i < 4; i++) {
;
	.dbg	line, "src/players.c", 11
	inc     _i
	jmp     L0018

	.dbg	line
.endproc

